# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15cdbf6b4db5b4a1ced2ff1d18eba4407853c571695874dbe6d0d05518c30b3138e01fc6019af921bc95ab9710cbdfb2a7ccf058c1c7f4811847b9be9eae3d24

test:
  secret_key_base: 41437e18e5347cfa39e119387d827364c6e515604d887298b2a6ed8500a50498f40f07a789b70926895efd0d3f2a4704c74c787377b41687a1e65981921998f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
